### PR TITLE
Add Godot Git Plugin

### PR DESCRIPTION
**Pull request by lishaduck**
While it doesn't work to push changes, it's quite useful to keep Git integrated in the editor instead of using the terminal. For me, it'll be nice to be able to close VSCode.

### CODE REVIEW

**Comment by lishaduck** [comment]
@MattsAttack, you might be interested in this.

**Comment by MattsAttack** [comment]
Seems useful. I've been using the desktop app and its super nice

**Comment by lishaduck** [comment]
> Seems useful. I've been using the desktop app and its super nice

Just tried it out. I like it. The UI feels _so_ 2020, but that's fine. I don't need something fancy for Git.

**Comment by lishaduck** [comment]
> > Seems useful. I've been using the desktop app and its super nice
> 
> Just tried it out. I like it. The UI feels _so_ 2020, but that's fine. I don't need something fancy for Git.

And... I switched. I really like GitLens in VSCode, so I tried out GitKraken. It's _amazing_! I love it already.

**Pull request merged**
